id: ICCFD35D3
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:10:08.330968
last_modified: 2023-02-08 15:10:08.331088
source_metadata:
  title: Laṅkāvatārasūtra
  language: zh
bases:
  84EB:
    base_file: 84EB.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
